name: admin-system

frontend:
  component: '@serverless/tencent-website'
  # more configuration for @serverless/tencent-website,
  # refer to: https://github.com/serverless-components/tencent-website/blob/master/docs/configure.md
  inputs:
    code:
      src: dist
      root: frontend
      envPath: src
      hook: npm run build
    env:
      # get api url after below api service deployed.
      apiUrl: ${backend.url}
    protocol: https
    hosts:
      - host: sls-admin.yugasun.com
        https:
          certId: ajzvLP82
          http2: off
          httpsType: 4
          # when https on, default should be -2
          # if http2 on, should be 2
          forceSwitch: -2

backend:
  component: '@serverless/tencent-egg'
  # more configuration for @serverless/tencent-website,
  # refer to: https://github.com/serverless-components/tencent-egg/blob/master/docs/configure.md
  inputs:
    code: ./backend
    functionName: admin-system
    role: QCS_SCFFull # You must add a role who can connect to your clound mysql
    functionConf:
      timeout: 120
      # you must set vpc config for mysql connnect
      vpcConfig:
        vpcId: vpc-6n5x55kb
        subnetId: subnet-4cvr91js
    apigatewayConf:
      protocols:
        - https
